# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BT1 Apartments
email: enquiry@bt1apartments.co.uk
description: > # this means to ignore newlines until "baseurl:"
  BT1 Apartments Belfast. With self-catering serviced apartments in the heart of
  Belfast Northern Ireland, including Ivy House, James Clow, Margarita Plaza and
  Titanic Quarter, you can book a serviced apartment from as little as £60 - £90
  per night and stay for years or just a few nights. Long term rates are
  negotiable depending on your budget and we will guarantee to beat any
  competitor rate in a similar location and facility.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bt1apartments.co.uk/" # the base hostname & protocol for your site
productions:
    - name: Game of Thrones
      src: /assets/images/productions/gameofthrones.jpg
      href: https://www.imdb.com/title/tt0944947
    - name: Robot Overlords
      src: /assets/images/productions/robotoverlords.jpg
      href: https://www.imdb.com/title/tt2145829
    - name: The Lodge
      src: /assets/images/productions/thelodge.jpg
      href: https://www.imdb.com/title/tt6176812
    - name: Morgan
      src: /assets/images/productions/morgan.jpg
      href: https://www.imdb.com/title/tt4520364
    - name: The Lost City of Z
      src: /assets/images/productions/thelostcityofz.jpg
      href: https://www.imdb.com/title/tt1212428
    - name: The Journey
      src: /assets/images/productions/thejourney.jpg
      href: https://www.imdb.com/title/tt4826674
    - name: Krypton
      src: /assets/images/productions/krypton.jpg
      href: https://www.imdb.com/title/tt4276624
    - name: Paula
      src: /assets/images/productions/paula.jpg
      href: https://www.imdb.com/title/tt6495880
    - name: Dave Allen at Peace
      src: /assets/images/productions/daveallenatpeace.jpg
      href: https://www.imdb.com/title/tt7912316

# Build settings
exclude:
    - gulpfile.js
    - bower.json
    - package.json
    - bower_components
    - node_modules
    - yarn.lock
    - .gitignore
