# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BT1 Apartments
email: enquiry@bt1apartments.co.uk
description: > # this means to ignore newlines until "baseurl:"
  BT1 Apartments Belfast. With apartments in the heart of Belfast, including
  Ivy House, James Clow, Margarita Plaza and Titanic Quarter, you can book a
  serviced apartment from as little as £50 - £90 per night and stay for years or
  just a few nights. Long term rates are negotiable depending on your budget and
  we will guarantee to beat any competitor rate in a similar location and facility.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bt1apartments.co.uk/" # the base hostname & protocol for your site

# Build settings
exclude: [gulpfile.js, bower.json, package.json, bower_components, node_modules]
